### ISSUE TITLE
FireFox backgrounds weren't working. 

### ISSUE THREAD

**Issue by rjksn** [briangonzalez/jquery.adaptive-backgrounds.js#30]
The backgrounds weren't working in FireFox. FF was taking the relative URL displaying it as an absolute URL with quotation marks around it, which caused the plugin to search for "https://example.com/%22https://example.com/resource/image.jpg%22" which would 404. So I added a bit to remove the double quotation marks. 

        <target_div style="background-image: url(resources/image.jpg);"></div>

        var getCSSBackground = function(){
          return $this.css('background-image')
                      .replace('url(','').replace(')','').replace(' ','').replace(/\"/g,'');
        };

**Comment by selfagency** [comment]
i can confirm experiencing this same issue in both firefox and firefox developer edition under os x.

**Comment by selfagency** [comment]
This is broken for me in Firefox as well but this solution did not work for me.

**Comment by briangonzalez** [comment]
Fixed via: https://github.com/briangonzalez/jquery.adaptive-backgrounds.js/commit/22c02cf30c32cff7a638e768c383eb24f71490b5
