### ISSUE TITLE
Call to adaptiveBackground.run is causing page to load (GET) a not found resource

### ISSUE THREAD

**Issue by taboca** [briangonzalez/jquery.adaptive-backgrounds.js#32]
Hi, I just noticed that if I disable the following: 
```
     $.adaptiveBackground.run();
```
It stops giving me an error related to a resource being queried against the localhost. In other words, there is an HTTP get being issued. This seems not to be entirely related to the adaptiveBackground. It seems that the adaptive's run is kicking something which is making my app to make that call — I wonder if you have an idea or if you can add a bit on what adaptiveBackground.run does.

**Comment by briangonzalez** [comment]
Fixed via: https://github.com/briangonzalez/jquery.adaptive-backgrounds.js/commit/22c02cf30c32cff7a638e768c383eb24f71490b5
