### ISSUE TITLE
Change rgb(x,x,x) to rgba(x,x,x,0.8)

### ISSUE THREAD

**Issue by realph** [briangonzalez/jquery.adaptive-backgrounds.js#34]
Is there an easy way to change the returned output of `rgb(x,x,x)` to `rgba(x,x,x, 0.8)`?

Any help is appreciated. Thanks in advance!

**Comment by znashty** [comment]
You can use an overlay div and set the plugin parent to that overlay div class, then change the css opacity to 0.8 or what ever you want.
