### ISSUE TITLE
exclude:

### ISSUE THREAD

**Issue by c9dd** [briangonzalez/jquery.adaptive-backgrounds.js#36]
Hi I can't seem to add to the default 'exclude:' options.
var defaults      = {
exclude: [ 'rgb(0,0,0)', 'rgb(255,255,255)', 'rgb(255, 255, 253)', 'rgb(247, 247, 247)' ]
};
$.adaptiveBackground.run(defaults);

Am I missing something?

**Comment by briangonzalez** [comment]
Do you have a demo?

**Comment by feint** [comment]
exclude doesn't work for me either.  Has very odd behaviour and changes the background of an item that shouldn't be excluded and the ones that should be excluded are left alone.
