### ISSUE TITLE
Loading Two Images

### ISSUE THREAD

**Issue by realph** [briangonzalez/jquery.adaptive-backgrounds.js#37]
Is there any reason that when using adaptive backgrounds, it seems to be loading two of the same image?

![screen shot 2015-05-22 at 00 34 36](https://cloud.githubusercontent.com/assets/2334951/7761168/6d51d86c-001a-11e5-8bd2-cad53e942a34.png)

Any help is appreciated. Thanks in advance!

**Comment by briangonzalez** [comment]
Are you using the background option?
