### ISSUE TITLE
Does not work in Firefox or IE

### ISSUE THREAD

**Issue by selfagency** [briangonzalez/jquery.adaptive-backgrounds.js#38]
This plugin does not function in Firefox or IE.

My code:

```
<section id="hero" style="background-image: url('/img/cover2.jpg')" data-adaptive-background="1" data-ab-css-background="1">
...
$(document).ready(function(){
  $.adaptiveBackground.run();
});
```

Chrome, OS X:
![screenshot 2015-06-02 14 24 38](https://cloud.githubusercontent.com/assets/2541728/7943544/1f33ea86-0933-11e5-98fb-f6ce0b083f97.png)

Chrome, Win 8:
![snap 2015-06-02 at 14 27 03 1011x649](https://cloud.githubusercontent.com/assets/2541728/7943625/aab1045e-0933-11e5-8146-d9f53c36b6d3.png)

Safari, OS X:
![screenshot 2015-06-02 14 24 59](https://cloud.githubusercontent.com/assets/2541728/7943550/29ce0440-0933-11e5-9472-c0150e4050c6.png)

Opera, Win 8:
![snap 2015-06-02 at 14 27 23 1302x484](https://cloud.githubusercontent.com/assets/2541728/7943632/b88022d6-0933-11e5-8323-1e3785dc3147.png)

Firefox, OS X:
![screenshot 2015-06-02 14 24 22](https://cloud.githubusercontent.com/assets/2541728/7943655/dd6f6a8e-0933-11e5-9730-b5126345cdae.png)

Firefox, Win 8:
![snap 2015-06-02 at 14 27 49 1194x592](https://cloud.githubusercontent.com/assets/2541728/7943650/d6c11034-0933-11e5-99b0-36d2d7c962f7.png)

Internet Explorer 11, Win 8:
![snap 2015-06-02 at 14 26 37 1365x614](https://cloud.githubusercontent.com/assets/2541728/7943662/e9e1cf78-0933-11e5-9805-d6573583362c.png)

**Comment by briangonzalez** [comment]
Fixed via: https://github.com/briangonzalez/jquery.adaptive-backgrounds.js/commit/22c02cf30c32cff7a638e768c383eb24f71490b5
