### ISSUE TITLE
Minimum image size?

### ISSUE THREAD

**Issue by etherElric** [briangonzalez/jquery.adaptive-backgrounds.js#42]
Hi,
I want to use a 300x118 image and it causes an error:
TypeError: rgb is null
return ((rgb[0]_299)+(rgb[1]_587)+(rgb[2]*114))/1000;
I tried with a bigger image and it works as expected. But I really need to be able to use it on this image format. Is there a limitation or is it fixable?
(I attached the 2 images I was trying it on)

![300x118](https://cloud.githubusercontent.com/assets/11576840/9063781/405c4a9c-3a97-11e5-842a-217229d72b8b.jpg)
![300x118-2](https://cloud.githubusercontent.com/assets/11576840/9063782/405ed906-3a97-11e5-8839-cf2175a907f7.jpg)

**Comment by AlfredJKwack** [comment]
I could not reproduce this issue. 
For the first image I got rgb(120,117,102) back as a color. See this [CodePen](http://codepen.io/anon/pen/BKwBeY)
Could you provide a working example on jsFiddle or codepen?

**Comment by AlfredJKwack** [comment]
This should now be fixed. 

There was an issue with the underlying [RGBaster.js](https://github.com/briangonzalez/rgbaster.js/commits/master/rgbaster.js) library which:

- [skipped a high number of pixels](https://github.com/briangonzalez/rgbaster.js/commit/46ad8e1eb7f4d12a2227f1b3bbc1f986459901b0#diff-c400952f68b4feb7cf2a2db087a1771f)
- only considered an [area of 300 by 150px](https://github.com/briangonzalez/rgbaster.js/commit/73c480b8344a4aadb178f9c78c479c8fa1031399#diff-c400952f68b4feb7cf2a2db087a1771f) of the source image 
- had some issues with [transparent pixels](https://github.com/briangonzalez/rgbaster.js/commit/c42f755e60a9abf5af01b95bad9ffd9c365f68ee#diff-c400952f68b4feb7cf2a2db087a1771f) and 
- didn't keep a list of [unique colors](https://github.com/briangonzalez/rgbaster.js/commit/d2315bb1d30303855e0f59bdb5158beff8029c22#diff-c400952f68b4feb7cf2a2db087a1771f). 

The latter issue is of no bearing to AD

Would you mind checking and validating if the issue still exists.
