### ISSUE TITLE
Is this line correct?

### ISSUE THREAD

**Issue by imakewebsites** [briangonzalez/jquery.adaptive-backgrounds.js#43]
// Helper function to calculate yiq - http://en.wikipedia.org/wiki/YIQ
var getYIQ = function(color){
   var rgb = data.color.match(/\d+/g); // <--- is this correct?
   return ((rgb[0]_299)+(rgb[1]_587)+(rgb[2]*114))/1000;
};

Shouldn't var rgb = color.match(/\d+/g); ?? (the color arg being passed into the function), not data.color.match(/\d+/g); (the callback data object's color) ??

**Comment by AlfredJKwack** [comment]
@imakewebsites I think you're right.
#49 fixes that.
