### ISSUE TITLE
If dominant color is the transparent color, returns "rgb()" and throws error

### ISSUE THREAD

**Issue by darrylyeo** [briangonzalez/jquery.adaptive-backgrounds.js#51]
For the below image of a square outline over a transparent background, the returned dominant color is "rgb()", and while attempting to parse the RGB values, the library throws this error:
`Uncaught TypeError: Cannot read property '0' of null`.

![image](https://cloud.githubusercontent.com/assets/13970789/14762518/4cfdb416-0931-11e6-9e0a-4474b3052570.png)

**Comment by antronic** [comment]
I have a same issue. ☹️

**Comment by heathercodes** [comment]
I have the same issue as well!

**Comment by AlfredJKwack** [comment]
Hi, 

This should now be fixed. 

There was an issue with the underlying [RGBaster.js](https://github.com/briangonzalez/rgbaster.js/commits/master/rgbaster.js) library which:

- [skipped a high number of pixels](https://github.com/briangonzalez/rgbaster.js/commit/46ad8e1eb7f4d12a2227f1b3bbc1f986459901b0#diff-c400952f68b4feb7cf2a2db087a1771f)
- only considered an [area of 300 by 150px](https://github.com/briangonzalez/rgbaster.js/commit/73c480b8344a4aadb178f9c78c479c8fa1031399#diff-c400952f68b4feb7cf2a2db087a1771f) of the source image 
- had some issues with [transparent pixels](https://github.com/briangonzalez/rgbaster.js/commit/c42f755e60a9abf5af01b95bad9ffd9c365f68ee#diff-c400952f68b4feb7cf2a2db087a1771f) and 
- didn't keep a list of [unique colors](https://github.com/briangonzalez/rgbaster.js/commit/d2315bb1d30303855e0f59bdb5158beff8029c22#diff-c400952f68b4feb7cf2a2db087a1771f). 

The latter issue is of no bearing to AD

Would you mind checking and validating if the issue still exists.

**Comment by darrylyeo** [comment]
@AlfredJKwack Well those would certainly be a problem! I can confirm that the issue no longer persists. Fantastic work.

**Comment by AlfredJKwack** [comment]
Thanks for the confirmation @darrylyeo 
Glad this solved the issue for you.
