### ISSUE TITLE
TypeError: null is not an object (evaluating 'rgb')

### ISSUE THREAD

**Issue by djrasmusp** [briangonzalez/jquery.adaptive-backgrounds.js#52]
I'm getting this error on one picture, every other picture works fine...
[http://7357.dk/kongsted/release/wild_child](http://7357.dk/kongsted/release/wild_child) doesn't work
[http://7357.dk/kongsted/release/whine_dat_remixes](http://7357.dk/kongsted/release/whine_dat_remixes) works ....
its the same file that renders it

Can anybody tell whats wrong ?

**Comment by djrasmusp** [comment]
[http://codepen.io/djrasmusp/pen/jrOOmX](http://codepen.io/djrasmusp/pen/jrOOmX)

**Comment by AlfredJKwack** [comment]
Hi.

This should now be fixed. 

There was an issue with the underlying [RGBaster.js](https://github.com/briangonzalez/rgbaster.js/commits/master/rgbaster.js) library which:

- [skipped a high number of pixels](https://github.com/briangonzalez/rgbaster.js/commit/46ad8e1eb7f4d12a2227f1b3bbc1f986459901b0#diff-c400952f68b4feb7cf2a2db087a1771f)
- only considered an [area of 300 by 150px](https://github.com/briangonzalez/rgbaster.js/commit/73c480b8344a4aadb178f9c78c479c8fa1031399#diff-c400952f68b4feb7cf2a2db087a1771f) of the source image 
- had some issues with [transparent pixels](https://github.com/briangonzalez/rgbaster.js/commit/c42f755e60a9abf5af01b95bad9ffd9c365f68ee#diff-c400952f68b4feb7cf2a2db087a1771f) and 
- didn't keep a list of [unique colors](https://github.com/briangonzalez/rgbaster.js/commit/d2315bb1d30303855e0f59bdb5158beff8029c22#diff-c400952f68b4feb7cf2a2db087a1771f). 

The latter issue is of no bearing to AD

Would you mind checking and validating if the issue still exists.

**Comment by AlfredJKwack** [comment]
Hi @djrasmusp,

I've [tweaked your codepen](https://codepen.io/anon/pen/xrWdzw) to validate. It appears to work as designed. Please do re-open if you see a further issue.

Rgds,
AJK
