### ISSUE TITLE
hello,how to use animate and opacity~？

### ISSUE THREAD

**Issue by sunsan05** [briangonzalez/jquery.adaptive-backgrounds.js#53]
I want use animate and opactiy on backgroundcolor

how can I use it with jquery.adaptive-backgrounds.js

**Comment by AlfredJKwack** [comment]
Hi Susan,

The latest pull request #70 added a transparent color feature.

With regards to animation, I think it would be helpful to understand more thoroughly what your intent is. Perhaps a [codePen to illustrate](https://codepen.io/anon/pen/qjEyjq?editors=0110) what you mean could help.

Assuming you want to change the value of a [css keyframe](https://css-tricks.com/almanac/properties/a/animation/) based on AD this could be rather tricky. There is an old [StackOverflow post](https://stackoverflow.com/questions/5105530/programmatically-changing-webkit-transformation-values-in-animation-rules) on the topic which outlines what would be involved. That would definitely goes beyond the scope of this library.
