### ISSUE TITLE
imageData varies greatly between bg image and img tag

### ISSUE THREAD

**Issue by NatalieFrecka** [briangonzalez/jquery.adaptive-backgrounds.js#55]
Using the exact same image as a background image and as an img src gave me vastly different results. The css background imageData came back with tons of empty pixel data, though the image had no transparent pixels in it. I'd say roughly the last third of the Uint8ClampedArray was just repeating zeros. The img tag was much more accurate. Though it's not perfect, I managed to normalize them by having `getCSSBackground()` function return an img element instead of the background source.

**Comment by AlfredJKwack** [comment]
Hi Natalie, could you post a codepen or something with an example? I'm not sure I'm able to replicate this.

**Comment by AlfredJKwack** [comment]
This should now be fixed. 

There was an issue with the underlying [RGBaster.js](https://github.com/briangonzalez/rgbaster.js/commits/master/rgbaster.js) library which:

- [skipped a high number of pixels](https://github.com/briangonzalez/rgbaster.js/commit/46ad8e1eb7f4d12a2227f1b3bbc1f986459901b0#diff-c400952f68b4feb7cf2a2db087a1771f)
- only considered an [area of 300 by 150px](https://github.com/briangonzalez/rgbaster.js/commit/73c480b8344a4aadb178f9c78c479c8fa1031399#diff-c400952f68b4feb7cf2a2db087a1771f) of the source image 
- had some issues with [transparent pixels](https://github.com/briangonzalez/rgbaster.js/commit/c42f755e60a9abf5af01b95bad9ffd9c365f68ee#diff-c400952f68b4feb7cf2a2db087a1771f) and 
- didn't keep a list of [unique colors](https://github.com/briangonzalez/rgbaster.js/commit/d2315bb1d30303855e0f59bdb5158beff8029c22#diff-c400952f68b4feb7cf2a2db087a1771f). 

The latter issue is of no bearing to AD

Would you mind checking and validating if the issue still exists.
