### ISSUE TITLE
Apply to font colour

### ISSUE THREAD

**Issue by jackjameshoward** [briangonzalez/jquery.adaptive-backgrounds.js#65]
Can this be adapted to change a font colour? 
I would like the font colour to contrast the image behind.

**Comment by AlfredJKwack** [comment]
Yes it can. 

When you run AD, it sets a property data-ab-color on each of the images. This property contains an rgb(x,y,z) value that you need. From there you can calculate the brightness and set the text to the appropriate color value.

Below is a very rough (read untested) implementation to give you an idea of what it would take.

```
         // Assume we have two text colors: light and dark
          var textColors = {
              normalizedTextColors:  {
                light:      "#fff",
                dark:       "#000"
              }
          }

         // Helper function to get brightness
          var getYIQ = function(color){
            var rgb = color.match(/\d+/g);
            return ((rgb[0]*299)+(rgb[1]*587)+(rgb[2]*114))/1000;
          };

         // Helper function to decide whether it's light or dark
          var getNormalizedTextColor = function (color){
            return getYIQ(color) >= 128 ? textColors.normalizedTextColors.dark : textColors.normalizedTextColors.light;
          };

         // Set the color of $myEl to the color contained 
         // in the data-ab-color property of $theImg on which AB ran.
          $myEl.css({ color: getNormalizedTextColor($(theImg).attr('data-ab-color')) });
```

You could of course use an entirely different library... something like [Background Check](http://www.kennethcachia.com/background-check/) developed by [Kenneth Cachia](https://github.com/kennethcachia)
