### ISSUE TITLE
Return wrong dominant color in chrome, firefox but alright in safari

### ISSUE THREAD

**Issue by mokku86** [briangonzalez/jquery.adaptive-backgrounds.js#66]
Hi, 

I was testing some artist image with your plugin, but I found out that some of my picture is picking the incorrect dominant color. This only occur on chrome and firefox. But safari seem to doing pretty nice.

Attached 2 images for your comparison.
![safari](https://cloud.githubusercontent.com/assets/21099457/17767616/41d58774-6563-11e6-94c1-d468b53935dd.png)
![chrome](https://cloud.githubusercontent.com/assets/21099457/17767617/41d85076-6563-11e6-9ca0-fd56e2ec3e8f.png)

**Comment by AlfredJKwack** [comment]
This should now be fixed. 

There was an issue with the underlying [RGBaster.js](https://github.com/briangonzalez/rgbaster.js/commits/master/rgbaster.js) library which:

- [skipped a high number of pixels](https://github.com/briangonzalez/rgbaster.js/commit/46ad8e1eb7f4d12a2227f1b3bbc1f986459901b0#diff-c400952f68b4feb7cf2a2db087a1771f)
- only considered an [area of 300 by 150px](https://github.com/briangonzalez/rgbaster.js/commit/73c480b8344a4aadb178f9c78c479c8fa1031399#diff-c400952f68b4feb7cf2a2db087a1771f) of the source image 
- had some issues with [transparent pixels](https://github.com/briangonzalez/rgbaster.js/commit/c42f755e60a9abf5af01b95bad9ffd9c365f68ee#diff-c400952f68b4feb7cf2a2db087a1771f) and 
- didn't keep a list of [unique colors](https://github.com/briangonzalez/rgbaster.js/commit/d2315bb1d30303855e0f59bdb5158beff8029c22#diff-c400952f68b4feb7cf2a2db087a1771f). 

The latter issue is of no bearing to AD

Would you mind checking and validating if the issue still exists.

**Comment by f1ss1on** [comment]
I'm having same issue. 
[Website](https://www.f1ss1on.com/bugatti.html)
I have the latest version being used.

**Comment by AlfredJKwack** [comment]
Hi @f1ss1on,

I can't seem to reproduce the issue. Chrome and Safari give the same rendering for the page on Mac OS... could you be a little [more explicit](https://github.com/briangonzalez/jquery.adaptive-backgrounds.js/wiki/How-to-Report-an-Issue).

**Comment by f1ss1on** [comment]
Hi @AlfredJKwack,

If you look at the link I provided, the color of the cars seem to be the most prominent colors. For some reason though only black and white are pulling as the dominant colors. 
[https://www.f1ss1on.com/bugatti.html](Sample Page)

Is there a way to adjust this?

**Comment by AlfredJKwack** [comment]
Hi @f1ss1on 

This is going to take a little explaining but essentially the most prominent colours are not what you think. There's a difference between what the eye percieves (the highlights) and the actual image. 

The [underlying library that actually determines the dominant color](https://github.com/briangonzalez/rgbaster.js) looks at each pixel and keeps track how often each color appears. It then orders that list and the color with the most pixels wins out. I've tested your images with a [couple](http://lokeshdhakar.com/projects/color-thief/) of [libraries](https://github.com/thephpleague/color-extractor) and they all pretty much give the same result as you saw here.

Sorry I can't be of any further help.

**Comment by AlfredJKwack** [comment]
Breaking this down a little more. 

Below are 4 different CodePen implementations with your images. None of them show exactly what you would expect though one does get pretty close.

- a [briangonzalez/jquery.adaptive-backgrounds.js](https://codepen.io/anon/pen/XarXBX/) implementation
- a [briangonzalez/rgbaster.js](https://codepen.io/anon/pen/ZJzOVV) implemenation. 
- a [lokesh/color-thief](https://codepen.io/anon/pen/wqwWGo) implementation
- a [leeoniya/RgbQuant.js](https://codepen.io/anon/pen/BdBLOq) imlementation. 

As you can see you have some options. 

Not all libraries are created equal. Each has its pros and cons. To my knowledge there is no other library like Adaptive Backgrounds built on top of either the Color-Thief or the RgbQuant libraries.

Those two libraries also have a slightly different aim from RGBaster, on top of which Adaptive Backgrounds is built. RgbQuant for instance is not built to give you a palette, that's a side effect more than anything else. It's aim is to [quantize](https://en.wikipedia.org/wiki/Quantization_(image_processing)) images through different algorythms.  Color-Thief is probably closer to what you're aiming for given your input images.It doesn't handle the background-coloring work for you though, you'd have to build it.

Hope this helps.
