### ISSUE TITLE
Update Readme.MD for shade variations features

### ISSUE THREAD

**Issue by AlfredJKwack** [briangonzalez/jquery.adaptive-backgrounds.js#73]
Now that we've merged #41 (Shade Variations by @DigitalKrony) we'll want to update the readme.

Default options section would be the logical place to insert a new bullet or somesutch.

The coded default options that would need to be added to the readme are:
```
shadeVariation:         false,
shadePercentage:        0,
shadeColors:            {
  light:      'rgb(255,255,255)',
  dark:       'rgb(0,0,0)' 
}
```

The readme edit could look something like this:

> - **shadeVariation** `blend|true|false` (default) option to shade the color of the parent ligher or darker (see shadePercentage) or blend the color of the parent with another color by a certain percentage (see shadeColors).
> - **shadePercentage** integer (default: `0`) sets the percentage of shading or blending used. Can be adjusted from -100 to 100.
> - **shadeColors** Object Literal ( default: `{light:'rgb(255,255,255)',dark:'rgb(0,0,0)'}` ) sets the color that will be used to blend the background color with. Two values are provided to account for the background color to be light or dark to start with.

@briangonzalez and @DigitalKrony any thoughts or edits on this?

**Comment by briangonzalez** [comment]
@AlfredJKwack Looks great. Ship it ;)

**Comment by DigitalKrony** [comment]
I'd have to do a test for negative numbers for the shadePercentage, but it's done on a 0 to 1 scale.

**Comment by AlfredJKwack** [comment]
Point taken. Did a quick test and yes, negative numbers work. The effect essentially does the blend in the opposite direction providing contrast. I'll update the doc and PR to reflect [-1...1].

**Comment by briangonzalez** [comment]
done :)
