### ISSUE TITLE
Demos not work

### ISSUE THREAD

**Issue by HawkonDK** [briangonzalez/jquery.adaptive-backgrounds.js#77]
when open one of the demos I can see the images but the background keep white

**Comment by honsa** [comment]
Which demos did you mean? 

The demo page is working for me in chrome 60.0.3112.113

http://briangonzalez.github.io/jquery.adaptive-backgrounds.js/

**Comment by HawkonDK** [comment]
yes also for me, but when you download the plugin and try to run the demo local, it doesn't work for me

**Comment by HawkonDK** [comment]
well find the issue, the links are broken.

so how can I chose what element to style with the color of the background-image ???

**Comment by AlfredJKwack** [comment]
Check the options in the Readme. You will want the one I pasted below. Note that it has to be a parent of the image. 

parent falsy (default: null) a CSS selector which denotes which parent to apply the background color to. By default, the color is applied to the parent one level up the DOM tree.
