### ISSUE TITLE
some images blocked by CORS policy

### ISSUE THREAD

**Issue by Wayne529** [briangonzalez/jquery.adaptive-backgrounds.js#81]
all the images in the same origin and domain,but some images can work well,some images can't work and the error is these images blocked by CORS policy.We are deal with all images in the domain,why some images are OK,some images are not Ok?

**Comment by AlfredJKwack** [comment]
Hi,

Could you provide a URL?

**Comment by Wayne529** [comment]
I am very happy to receive your reply.Thank u!

**Comment by Wayne529** [comment]
I am very happy to receive your reply. Thank u!!! And the problem had been resolved by our PHPer,maybe they deal with images across origin get some wrong.I'll close this problem,thank you!
