### ISSUE TITLE
Any change of Video support

### ISSUE THREAD

**Issue by utx0** [briangonzalez/jquery.adaptive-backgrounds.js#82]
Any change of Video support at all?

**Comment by AlfredJKwack** [comment]
Hi @lukekhamilton,

You mean reading ahead to every frame, calculating the total pixels, then making one background for the entire time? Or did you have in mind a smoothly shifting background by sampling ahead a few seconds and then transitioning from one colour to the next in the hopes of getting something like the [Philips Ambilight](https://youtu.be/s9uUNj0IP8I?t=14) effect...

Alas I believe that in either case this library is not what you are looking for. 

I did see one [nice CodePen that does the Ambilight effect](https://codepen.io/MyXoToD/pen/KbADu). I guess that you could give that a spin. There's another example over at [chikuyonok](http://media.chikuyonok.ru/ambilight/).

Good luck
