### ISSUE TITLE
Rerunning $.adaptiveBackground.run(); ?

### ISSUE THREAD

**Issue by Ralph-Imholz** [briangonzalez/jquery.adaptive-backgrounds.js#83]
Love the code, but I'm having a slight issue!

I want to run the adaptive background code multiple times per session, but everytime I rerun `$.adaptiveBackground.run();` the color that is generated becomes less and less saturated.

Am I not supposed to rerun that function or is there a different way to regenerate the dominant colors?

Thanks in advance.

**Comment by AlfredJKwack** [comment]
Hi,

I’m surprised that would occur. Would you mind loading your image on imgur and I’ll try to replicate the issue. If you have a codepen as an example that would be great also. Lastly can you say what browser and OS you are running?

Thanks.

**Comment by Ralph-Imholz** [comment]
Thanks for the quick reply!

https://codepen.io/ralphimholz/pen/pdmwBj

I made this codepen to demonstrate my issue, but in trying to replicate it I had a different result. This could be because the product I was working on is significantly more intricate than this codepen.

Still, I am seeing different results than I expected. When you change the image the adaptive-backgrounds code doesn't seem to run, or at least, nothing visually changes and no errors are thrown. I would expect that after changing the image and rerunning $.adaptiveBackround.run() the background would change.

Also, when you change the image before ever running adaptive-backgrounds nothing seems to be happening either.

**Edit: nvm I wasn't loading the image with CORS... Still I can't reproduce the issue I was having in the first place with the changing of saturation, I'll get back to you later after I do some more testing I guess.**

**Edit2: everything works fine. I might be going insane. This issue can be closed.**
